# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89a8ffd99c8ac54d8c2a2c703a9caad328493db40c1b0688d2575975511141babb462966dbe3209bfef3b267e2837e46e0351758840bf972921ac616def27c40

test:
  secret_key_base: 200a80cb3ef09b2ef4065634044c517a77603b2671cd1aebe5a6ecd1c3fb279834ba138d7c0a6b675acbc7bb698b4ab590a9bdde6d52e25e2708b35610860df4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
